export const inputs = [
  [
    {
      type: "email",
      label: "Email",
      name: "email",
      placeholder: "Digite seu e-mail",
      width: "48%",
    },
    {
      type: "text",
      label: "Nome",
      name: "name",
      placeholder: "Digite o seu nome",
      width: "48%",
    },
    {
      type: "password",
      label: "Senha",
      name: "password",
      placeholder: "Digite a sua senha",
      width: "48%",
    },
    {
      type: "password",
      label: "Confirme a senha",
      name: "confirmPassword",
      placeholder: "Confirme a sua senha",
      width: "48%",
    },
    {
      type: "text",
      label: "Você é...",
      name: "category",
      placeholder: "Confirme a sua senha",
      width: "48%",
    },
  ],
  [
    {
      type: "text",
      label: "CNPJ",
      name: "cnpj",
      placeholder: "Informe o seu CNPJ",
      width: "48%",
    },
    {
      type: "text",
      label: "Razão Social",
      name: "razaoSocial",
      placeholder: "Informe a razão social da empresa",
      width: "48%",
    },
    {
      type: "text",
      label: "Site",
      name: "site",
      placeholder: "Digite o endereço do site",
      width: "48%",
    },
    {
      type: "text",
      label: "Telefone de contato",
      name: "telefone",
      placeholder: "Informe o telefone comercial",
      width: "48%",
    },
    {
      type: "text",
      label: "CEP da Matriz",
      name: "cep",
      placeholder: "Informe o CEP da matriz",
      width: "48%",
    },
    {
      type: "number",
      label: "Número",
      name: "numero",
      placeholder: "000",
      width: "22%",
    },
    {
      type: "text",
      label: "Complemento",
      name: "complemento",
      placeholder: "Apto, Loja",
      width: "22%",
    },
  ],
  [
    {
      type: "text",
      label: "Origem",
      name: "origem",
      placeholder: "Informe uma cidade de origem",
      width: "48%",
    },
    {
      type: "text",
      label: "Destino",
      name: "destino",
      placeholder: "Informe uma cidade de destino",
      width: "48%",
    },
    {
      type: "number",
      label: "Quantidade de transportes ao mês",
      name: "quantidade",
      placeholder: "Informe a quantidade média ao mês",
      width: "48%",
    },
  ],
];
